site_name: 雲簇芳年

theme:
  name: material
  language: zh-TW
  palette:
    scheme: default
    primary: purple
    accent: indigo
  font:
    text: Noto Serif TC
    code: Noto Sans Mono

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences

nav:
  - 首頁: index.md
  - 周國:
      - 簡介: zhou/index.md
      - 後宮:
          - 後宮玉碟: zhou/harem/index.md
          - 後宮玩家: zhou/harem/players/index.md
          - 後宮主要NPC: zhou/harem/main-npc/index.md
          - 後宮工具人: zhou/harem/tools/index.md
      - 世家:
          - 世家家族總覽: zhou/clans/index.md
          - 世家玩家: zhou/nobles/players/index.md
          - 世家主要NPC: zhou/nobles/main-npc/index.md
      - 其他NPC: zhou/other-npc/index.md
  - 殷國:
      - 簡介: yin/index.md
      - 世家:
          - 世家家族總覽: yin/clans/index.md
      - NPC:
          - NPC總覽: yin/npc/index.md

